export const BUSINESS_LOCATION_DATA = 'BUSINESS_LOCATION_DATA';
export const BUSINESS_CATEGORIES_DATA = 'BUSINESS_CATEGORIES_DATA';
export const PROMOTIONS_LOCATION_DATA = 'PROMOTIONS_LOCATION_DATA';
export const PROMOTION_FLAG = 'PROMOTION_FLAG';
