# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'balehuApp' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for balehuApp
  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'GoogleMobileVision/Detector', '~> 1.1.0'
  pod 'GoogleMobileVision/MVDataOutput', '~> 1.1.0'
  pod 'GoogleMobileVision/FaceDetector', '~> 1.1.0'

  pod 'react-native-camera', path: '../node_modules/react-native-camera'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
